
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OrgMan.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class AccountToMandator : IEntityUID
{

    public System.Guid UID { get; set; }

    public System.DateTimeOffset SysInsertTime { get; set; }

    public System.Guid SysInsertAccountUID { get; set; }

    public System.DateTimeOffset SysUpdateTime { get; set; }

    public System.Guid SysUpdateAccountUID { get; set; }

    public System.Guid MandatorUID { get; set; }

    public System.Guid AccountUID { get; set; }



    public virtual Account Account { get; set; }

    public virtual Mandator Mandator { get; set; }

}

}
