

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OrgMan.DataModel
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class OrgManEntities : DbContext
{
    public OrgManEntities()
        : base("name=OrgManEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Account> Account { get; set; }

    public virtual DbSet<AccountToMandator> AccountToMandator { get; set; }

    public virtual DbSet<Adress> Adress { get; set; }

    public virtual DbSet<CommunicationType> CommunicationType { get; set; }

    public virtual DbSet<Country> Country { get; set; }

    public virtual DbSet<EmailAdress> EmailAdress { get; set; }

    public virtual DbSet<EmailAdressToPerson> EmailAdressToPerson { get; set; }

    public virtual DbSet<Login> Login { get; set; }

    public virtual DbSet<Mandator> Mandator { get; set; }

    public virtual DbSet<Meeting> Meeting { get; set; }

    public virtual DbSet<MemberInformation> MemberInformation { get; set; }

    public virtual DbSet<MemberInformationToMembership> MemberInformationToMembership { get; set; }

    public virtual DbSet<Membership> Membership { get; set; }

    public virtual DbSet<Person> Person { get; set; }

    public virtual DbSet<Phone> Phone { get; set; }

    public virtual DbSet<PhoneToPerson> PhoneToPerson { get; set; }

    public virtual DbSet<Salutation> Salutation { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

}

}

