//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgMan.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.EmailAdressToPerson = new HashSet<EmailAdressToPerson>();
            this.PhoneToPerson = new HashSet<PhoneToPerson>();
        }
    
        public System.Guid UID { get; set; }
        public System.DateTimeOffset SysInsertTime { get; set; }
        public System.Guid SysInsertAccountUID { get; set; }
        public System.DateTimeOffset SysUpdateTime { get; set; }
        public System.Guid SysUpdateAccountUID { get; set; }
        public System.Guid MandatorUID { get; set; }
        public System.Guid SalutationUID { get; set; }
        public System.Guid AccountUID { get; set; }
        public System.Guid MemberInformationUID { get; set; }
        public System.Guid AdressUID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Comment { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Adress Adress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailAdressToPerson> EmailAdressToPerson { get; set; }
        public virtual Mandator Mandator { get; set; }
        public virtual MemberInformation MemberInformation { get; set; }
        public virtual Salutation Salutation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhoneToPerson> PhoneToPerson { get; set; }
    }
}
