//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgMan.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone : IEntityUID
    {
        public System.Guid UID { get; set; }
        public System.DateTimeOffset SysInsertTime { get; set; }
        public System.Guid SysInsertAccountUID { get; set; }
        public Nullable<System.DateTimeOffset> SysUpdateTime { get; set; }
        public Nullable<System.Guid> SysUpdateAccountUID { get; set; }
        public System.Guid CommunicationTypeUID { get; set; }
        public System.Guid IndividualPersonUID { get; set; }
        public string Number { get; set; }
        public bool IsMain { get; set; }
    
        public virtual CommunicationType CommunicationType { get; set; }
        public virtual IndividualPerson IndividualPerson { get; set; }
    }
}
