
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OrgMan.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class PhoneToPerson : IEntityUID
{

    public System.Guid UID { get; set; }

    public System.DateTimeOffset SysInsertTime { get; set; }

    public System.Guid SysInsertAccountUID { get; set; }

    public System.DateTimeOffset SysUpdateTime { get; set; }

    public System.Guid SysUpdateAccountUID { get; set; }

    public System.Guid PhoneUID { get; set; }

    public System.Guid PersonUID { get; set; }

    public System.Guid CommunicationTypeUID { get; set; }

    public bool MainPhoneNumber { get; set; }



    public virtual CommunicationType CommunicationType { get; set; }

    public virtual Person Person { get; set; }

    public virtual Phone Phone { get; set; }

}

}
